### ISSUE TITLE
visualization-ghost orbital geometry plot

### ISSUE THREAD

**Issue by arsalan-akhtar** [pfebrer96/sisl#28]
Hey pol 
There is bug for geometry plot when use ghost orbital with negative Z (atomic number)

Cheersssssss!!!

**Comment by pfebrer** [comment]
@zerothi does it make sense that `Atom` (and `PeriodicTable`) are aware that negative Z represents a ghost atom? Is this standard?

And `sisl.Atom(-1)` returns an atom with symbol "Ghost H" instead of "fa", for example.

This is part of the problem why the bug is happening.

**Comment by pfebrer** [comment]
Arsalan the bug is solved, now ghost atoms are shown with a bit of transparency. Thanks for the first issue here that is not mine! :)

**Comment by zerothi** [comment]
> @zerothi does it make sense that `Atom` (and `PeriodicTable`) are aware that negative Z represents a ghost atom? Is this standard?
> 
> And `sisl.Atom(-1)` returns an atom with symbol "Ghost H" instead of "fa", for example.
> 
> This is part of the problem why the bug is happening.

This is because this is Siesta's nomenclature. Alternatively I should create a subclass that is an `AtomGhost` class and this would carry through. However, it does require some other changes here and there. But you are right. That would probably be better to change for a more consistent usage.
