### ISSUE TITLE
Can't generate PDOS plot from fdf.

### ISSUE THREAD

**Issue by pfebrer** [pfebrer96/sisl#36]
It looks for file `SystemLabel.pdos` instead of `SystemLabel.PDOS`. I think at some point the rule for the PDOS file changed, because it was working previously.

**Comment by pfebrer** [comment]
> I think at some point the rule for the PDOS file changed, because it was working previously.

Did it, @zerothi?

**Comment by zerothi** [comment]
I don't think so ;)

If you do `gitk sisl/io/siesta/pdos.py` you'll see that only 1 commit later than the argumentparser addition was made. What is the error?

**Comment by pfebrer** [comment]
Hmm ok maybe I didn't try before, or I have changed something. It's not an error, it's a bug in my implementation.

I take the systemlabel from the fdf and then I add the suffix of the sile that I want to look for. But in this case the suffixes are lowercase and SIESTA writes them as uppercase (i.e. .pdos vs .PDOS), so it doesn't find the file. I will change it to do a case insensitive search probably.

**Comment by zerothi** [comment]
Hmm, I don't know exactly how you are doing things. ;)

I do something like this:
```python
        f = self.dir_file(self.get('SystemLabel', default='siesta') + '.nc')
```
for fdf siles

**Comment by pfebrer** [comment]
Yes, this is what I do basically:

```python
for rule in sisl.get_sile_rules(cls=sile_type):
    filename = fdf_sile.get('SystemLabel', default='siesta') + f'.{rule.suffix}'
    try:
        path = fdf_sile.dir_file(filename, results_path)
```
(https://github.com/zerothi/sisl/blob/274c32adeaebd5945a34ee751b0461f750fb415e/sisl/viz/plotly/plot.py#L886-L889)

where `sile_type` is the sile class that is associated with the specific setting. I.e. `pdos_file` has a `dtype` of `pdosSileSiesta`. Then the rules to search for a valid file are `.pdos` and `.pdos.xml`, but SIESTA writes `.PDOS` instead so it doesn't find the PDOS file.

**Comment by zerothi** [comment]
Yeah, ok. That is because the sile has `case=False` in its definition.

I have just corrected this in the latest commit. But generally you need to check whether you have `.case` being true/false, and if false you have to check *any* combination of the suffix. That was why it was stored in lower case.

**Comment by pfebrer** [comment]
Thanks! I will open a new issue for this then.

**Comment by zerothi** [comment]
But I think it is fixed, no?

**Comment by pfebrer** [comment]
This issue in particular yes, but I need to make sure that I search for all possibilities when `case = False` (if I understood correctly)

**Comment by zerothi** [comment]
Ah, ok, true

**Comment by pfebrer** [comment]
Actually I thought about this and maybe the functionality that I need here can be part of the `fdfSile`.

Same as there is `fdfSile.read_grid("VT")`, there could be a `fdfSile.get_sile("VT")`, which would get you the sile instead of returning the grid directly. This could be useful to get PDOS siles (as in this issue) or any other sile that can be related to the fdf.
This could exist not only in fdfs but also in other files that play a similar role in other codes.

What do you think?

**Comment by zerothi** [comment]
You mean generally `get_sile_class`?

My idea was that this could leverage these use-cases. And there is the possibility of adding file specifications using `filename{specifier}` to allow default search spaces.

**Comment by pfebrer** [comment]
Hmm not quite I think.

Imagine I have an fdf file:

```python
fdf = sisl.get_sile("my_run.fdf")
```

And now I want to get its PDOS output. What I'm saying is that:

```python
PDOS = sisl.get_sile("Systemlabel.PDOS")
```

and

```python
PDOS = fdf.get_sile("PDOS")
```

could be equivalent.

**Comment by zerothi** [comment]
Hmm, I am not too fond of this.

What I would suggest is that we for each *code* have a main class, sort of like the `BaseSile` that can be used to determine bases and sub-classes. Then one can search for siles belonging to a code via this.

The specifier can be used exactly for what you want, but requires that siles don't change...

**Comment by pfebrer** [comment]
Well in fact what I would need is something like `fdf.get_sile(pdosSileSiesta)`, so that I actually pass the class. I proposed `fdf.get_sile("PDOS")` because I thought it was more user friendly.

> What I would suggest is that we for each code have a main class, sort of like the BaseSile that can be used to determine bases and sub-classes. Then one can search for siles belonging to a code via this.

Sounds great to me!

**Comment by zerothi** [comment]
> Well in fact what I would need is something like `fdf.get_sile(pdosSileSiesta)`, so that I actually pass the class. I proposed `fdf.get_sile("PDOS")` because I thought it was more user friendly.

Ok, now I think I understand what you want.

You basically want a wrapper that returns the `fdf.get("SystemLabel", default="siesta") / ".PDOS"` or something similar.

Hmm. I am thinking about how this would translate to other codes.
I really don't want a Siesta only use case that can't be used for other codes.

Perhaps if we could try a similar scheme for VASP or another code we could see how it should be implemented?

**Comment by pfebrer** [comment]
> You basically want a wrapper that returns the fdf.get("SystemLabel", default="siesta") / ".PDOS" or something similar.

Hmm yes but only if that file exists, and also take in consideration that there are multiple valid suffixes. I.e. if I do `fdf.get_sile(pdosSileSiesta)` and there is no `.PDOS` file but there is a `.PDOS.xml` I would like the .PDOS.xml  file to be returned.

In other words, a way to look for the output files that are related to a certain fdf.

**Comment by zerothi** [comment]
> > You basically want a wrapper that returns the fdf.get("SystemLabel", default="siesta") / ".PDOS" or something similar.
> 
> Hmm yes but only if that file exists, and also take in consideration that there are multiple valid suffixes. I.e. if I do `fdf.get_sile(pdosSileSiesta)` and there is no `.PDOS` file but there is a `.PDOS.xml` I would like the .PDOS.xml file to be returned.
> 
> In other words, a way to look for the output files that are related to a certain fdf.

This is really a corner case `Sile` not many (if any other) can read the same content in two different files.

Perhaps a better idea would be to add rules directly to classes (as a permanent internal variable).
In that way you can get the suffix rules and loop them by only having the class.
