### ISSUE TITLE
Make splot better

### ISSUE THREAD

**Issue by pfebrer** [pfebrer96/sisl#8]
Right now the `splot` command for the command line it's just a very simple thing.

It's a first implementation as a test and I hope Nick doesn't see it because he will get angry. I'm not using the workflows he developed for parsing arguments because I don't understand it yet.

Here are some things I would like the `splot` command to do:

- [x] Plot a file
- [x] Save the plot
- [x] Accept settings as arguments in the command line?
- [x] Allow users to use presets they have defined previously (complex settings can not be passed through command line)

**Comment by pfebrer** [comment]
Done, the only thing left is the possibility to apply methods on plots from the CLI, which will be a new issue.

**Comment by pfebrer96** [comment]
Here it is https://github.com/pfebrer96/sisl/issues/17
